load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "aa",
    srcs = [
        "include/aa/error.hpp",
        "include/aa/internal.hpp",
        "include/aa/options.hpp",
        "include/aa/parser.hpp",
    ],
    hdrs = [
        "include/aa.hpp",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
)
